
package(default_visibility = ["//algorithms:__subpackages__"])

cc_library(
    name = "parse_command_line",
    hdrs = ["parse_command_line.h"],
    deps = [
        "@parlaylib//parlay:parallel",
        "@parlaylib//parlay:primitives",
    ],
)