include ../algorithms/bench/parallelDefsANN

bvec_to_u8bin : bvec_to_u8bin.cpp
	$(CC) $(CFLAGS) -o bvec_to_u8bin bvec_to_u8bin.cpp $(LFLAGS) 

compute_groundtruth : compute_groundtruth.cpp
	$(CC) $(CFLAGS) -o compute_groundtruth compute_groundtruth.cpp $(LFLAGS) 

crop : crop.cpp
	$(CC) $(CFLAGS) -o crop crop.cpp $(LFLAGS) 