include ../algorithms/bench/parallelDefsANN

vec_to_bin : vec_to_bin.cpp
	$(CC) $(CFLAGS) -o vec_to_bin vec_to_bin.cpp $(LFLAGS) 

compute_groundtruth : compute_groundtruth.cpp
	$(CC) $(CFLAGS) -o compute_groundtruth compute_groundtruth.cpp $(LFLAGS) 

compute_range_groundtruth : compute_range_groundtruth.cpp
	$(CC) $(CFLAGS) -o compute_range_groundtruth compute_range_groundtruth.cpp $(LFLAGS) 

range_utils : range_utils.cpp
	$(CC) $(CFLAGS) -o range_utils range_utils.cpp $(LFLAGS) 

crop : crop.cpp
	$(CC) $(CFLAGS) -o crop crop.cpp $(LFLAGS) 

random_sample : random_sample.cpp
	$(CC) $(CFLAGS) -o random_sample random_sample.cpp $(LFLAGS) 

graph_stats : graph_stats.cpp
	$(CC) $(CFLAGS) -o graph_stats graph_stats.cpp $(LFLAGS) 

threshold_histo : threshold_histo.cpp
	$(CC) $(CFLAGS) -o threshold_histo threshold_histo.cpp $(LFLAGS) 

data_union : data_union.cpp
	$(CC) $(CFLAGS) -o data_union data_union.cpp $(LFLAGS) 

match_base_search : match_base_search.cpp
	$(CC) $(CFLAGS) -o match_base_search match_base_search.cpp $(LFLAGS) 
	