include ../../algorithms/bench/parallelDefsANN

REQUIRE = utils/point_range.h ../ivf/ivfGraph.h ../ivf/ivf.h utils/check_nn_recall.h  utils/parse_results.h utils/graph.h utils/point_range.h
BENCH = ivfGraph

include ../bench/MakeBench
