include ../bench/parallelDefsANN

REQUIRE = ../utils/beamSearch.h index.h  ../utils/check_nn_recall.h ../utils/NSGDist.h ../utils/parse_results.h ../utils/graph.h ../utils/point_range.h ../utils/euclidian_point.h ../utils/mips_point.h ../utils/jl_point.h
BENCH = neighbors

include ../bench/MakeBench
