include ../../algorithms/bench/parallelDefsANN

eval_graphs : eval_graphs.cpp
	$(CC) $(CFLAGS) -o eval_graphs eval_graphs.cpp $(LFLAGS) 


eval_pointrange : eval_pointrange.cpp
	$(CC) $(CFLAGS) -o eval_pointrange eval_pointrange.cpp $(LFLAGS) 