include ../bench/parallelDefsANN

REQUIRE = ../utils/beamSearch.h ../utils/doubling_search.h ../utils/range_search.h ../../algorithms/vamana/index.h  ../utils/check_nn_recall.h ../utils/NSGDist.h ../utils/parse_results.h ../utils/graph.h ../utils/point_range.h ../utils/check_range_recall.h
BENCH = range

include ../bench/MakeBench
