include ../bench/parallelDefsANN

REQUIRE = ../utils/beamSearch.h ../../algorithms/vamana/index.h  ../utils/check_nn_recall.h ../utils/NSGDist.h ../utils/parse_results.h ../utils/graph.h ../utils/point_range.h
BENCH = range

include ../bench/MakeBench
